### ISSUE TITLE
Support `gateway.ethswarm.org/<<hash>>` resolution

### ISSUE THREAD

**Issue by AuHau** [ethersphere/gateway#113]
I would propose to allow hash in the root path either instead of the `/access` subpath or as an addition. I think it makes more sense.

Also, the ENS manager currently resolves Swarm links to this address.

**Comment by agazso** [comment]
ENS currently points to `/bzz/<hash>` links. See also https://github.com/ethersphere/gateway/issues/94, https://github.com/ethersphere/gateway/issues/104 and https://github.com/ethersphere/gateway/issues/105

As far as I know this has already been implemented but has not been deployed yet.

**Comment by AuHau** [comment]
You are right, I got confused somehow. Thanks!
