### ISSUE TITLE
Automatically clean Swarm addresses

### ISSUE THREAD

**Issue by Eknir** [ethersphere/gateway#126]
A Swarm address should be 64 or 128 hex. However, a user might add a space or an enter before or after the address, or start with a `0x`. It would be good to sanitize the Swarm addresses in the gateway from such common errors. I stumbled upon this error myself last weekend and it took me some time to figure out why this correctly-pasted Swarm address was not accepted:
![image](https://user-images.githubusercontent.com/33000441/145774732-f352c137-62b4-445b-8d10-ec7264949342.png)

**Comment by agazso** [comment]
Fixed in https://github.com/ethersphere/gateway/pull/132
