### ISSUE TITLE
Using `/bzz` link instead of `/access` shows link does not exist

### ISSUE THREAD

**Issue by agazso** [ethersphere/gateway#94]
Instead of `Found your file`

For example:

https://gateway.ethswarm.org/bzz/a734e6c14d8b5ef9ea537b67b5b637cb9c3c3d634fc0c5bd419a6f1d3ae073d6/

vs

https://gateway.ethswarm.org/access/a734e6c14d8b5ef9ea537b67b5b637cb9c3c3d634fc0c5bd419a6f1d3ae073d6/

**Comment by vojtechsimetka** [comment]
But this is correct. The /bzz endpoint does not exist on the gateway. That being said, we could mount the same component to both these endpoints (and /download as well)

**Comment by significance** [comment]
we need to host websites through the gateway too

for this the links `download.gateway.ethswarm.org/...` do not make sense

**Comment by vojtechsimetka** [comment]
I agree with you @significance , but this is a slightly different discussion IMHO

**Comment by significance** [comment]
agree!
