### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by mozfc** [ethersphere/gateway#98]
![image](https://user-images.githubusercontent.com/20202485/124051773-b5111800-da4f-11eb-8928-fd4754be162a.png)
![image](https://user-images.githubusercontent.com/20202485/124051824-cb1ed880-da4f-11eb-9204-d2b1a687db61.png)

How to proxy in this project ？

**Comment by agazso** [comment]
You are not supposed to use `*.gateway.ethswarm.org` nodes (unless you are Swarm Foundation). I suggest to use it with your own Bee nodes instead.
